cargo-features = ["edition2024"]
workspace = { members = ["browser_core"] }

[package]
name = "browser_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
noli = {git = "https://github.com/hikalium/wasabi.git", branch = "for_saba"}
